server:
  port: 8084

spring:
  application:
    name: stock
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: stock-product
      order-group-id: stock-order
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.eda.common.event
  datasource:
    url: jdbc:postgresql://localhost:5432/eda
    username: eda
    password: eda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: stock
        globally_quoted_identifiers: true
        hbm2ddl:
          create_namespaces: true
